# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistas/ventanatomarorden.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTomarOrden(object):
    def setupUi(self, FormTomarOrden):
        FormTomarOrden.setObjectName("FormTomarOrden")
        FormTomarOrden.resize(768, 498)
        self.horizontalLayout_orden = QtWidgets.QHBoxLayout(FormTomarOrden)
        self.horizontalLayout_orden.setObjectName("horizontalLayout_orden")
        self.lay_menu_izq = QtWidgets.QVBoxLayout()
        self.lay_menu_izq.setObjectName("lay_menu_izq")
        self.label = QtWidgets.QLabel(FormTomarOrden)
        self.label.setObjectName("label")
        self.lay_menu_izq.addWidget(self.label)
        self.tbl_menu_disponible = QtWidgets.QTableView(FormTomarOrden)
        self.tbl_menu_disponible.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_menu_disponible.setObjectName("tbl_menu_disponible")
        self.lay_menu_izq.addWidget(self.tbl_menu_disponible)
        self.btn_ver_imagen = QtWidgets.QPushButton(FormTomarOrden)
        self.btn_ver_imagen.setObjectName("btn_ver_imagen")
        self.lay_menu_izq.addWidget(self.btn_ver_imagen)
        self.formlayout = QtWidgets.QFormLayout()
        self.formlayout.setObjectName("formlayout")
        self.label1 = QtWidgets.QLabel(FormTomarOrden)
        self.label1.setObjectName("label1")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.txt_notas_cliente = QtWidgets.QLineEdit(FormTomarOrden)
        self.txt_notas_cliente.setObjectName("txt_notas_cliente")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_notas_cliente)
        self.label2 = QtWidgets.QLabel(FormTomarOrden)
        self.label2.setObjectName("label2")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.spin_cantidad = QtWidgets.QSpinBox(FormTomarOrden)
        self.spin_cantidad.setMinimum(1)
        self.spin_cantidad.setObjectName("spin_cantidad")
        self.hboxlayout.addWidget(self.spin_cantidad)
        self.btn_add_platillo = QtWidgets.QPushButton(FormTomarOrden)
        self.btn_add_platillo.setObjectName("btn_add_platillo")
        self.hboxlayout.addWidget(self.btn_add_platillo)
        self.formlayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.hboxlayout)
        self.lay_menu_izq.addLayout(self.formlayout)
        self.horizontalLayout_orden.addLayout(self.lay_menu_izq)
        self.lay_orden_der = QtWidgets.QVBoxLayout()
        self.lay_orden_der.setObjectName("lay_orden_der")
        self.label3 = QtWidgets.QLabel(FormTomarOrden)
        self.label3.setObjectName("label3")
        self.lay_orden_der.addWidget(self.label3)
        self.tbl_orden_actual = QtWidgets.QTreeView(FormTomarOrden)
        self.tbl_orden_actual.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_orden_actual.setObjectName("tbl_orden_actual")
        self.lay_orden_der.addWidget(self.tbl_orden_actual)
        self.btn_eliminar_platillo = QtWidgets.QPushButton(FormTomarOrden)
        self.btn_eliminar_platillo.setObjectName("btn_eliminar_platillo")
        self.lay_orden_der.addWidget(self.btn_eliminar_platillo)
        self.lbl_total = QtWidgets.QLabel(FormTomarOrden)
        self.lbl_total.setStyleSheet("font-size: 22px; font-weight: bold; color: #2E7D32;")
        self.lbl_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_total.setObjectName("lbl_total")
        self.lay_orden_der.addWidget(self.lbl_total)
        self.btn_crear_orden = QtWidgets.QPushButton(FormTomarOrden)
        self.btn_crear_orden.setStyleSheet("background-color: #4CAF50; color: white; padding: 15px; font-size: 14px; font-weight: bold;")
        self.btn_crear_orden.setObjectName("btn_crear_orden")
        self.lay_orden_der.addWidget(self.btn_crear_orden)
        self.horizontalLayout_orden.addLayout(self.lay_orden_der)

        self.retranslateUi(FormTomarOrden)
        QtCore.QMetaObject.connectSlotsByName(FormTomarOrden)

    def retranslateUi(self, FormTomarOrden):
        _translate = QtCore.QCoreApplication.translate
        FormTomarOrden.setWindowTitle(_translate("FormTomarOrden", "TECLUSA - Crear Nueva Orden"))
        self.label.setText(_translate("FormTomarOrden", "<b>Catálogo de Menú</b>"))
        self.btn_ver_imagen.setText(_translate("FormTomarOrden", "Ver Imagen del Platillo Seleccionado"))
        self.label1.setText(_translate("FormTomarOrden", "Notas (Ej. Sin cebolla):"))
        self.txt_notas_cliente.setPlaceholderText(_translate("FormTomarOrden", "Opcional..."))
        self.label2.setText(_translate("FormTomarOrden", "Cantidad:"))
        self.btn_add_platillo.setText(_translate("FormTomarOrden", "Añadir a Orden"))
        self.label3.setText(_translate("FormTomarOrden", "<b>Desglose de Orden Actual</b>"))
        self.btn_eliminar_platillo.setText(_translate("FormTomarOrden", "Eliminar Platillo Seleccionado"))
        self.lbl_total.setText(_translate("FormTomarOrden", "Total a Pagar: $0.00"))
        self.btn_crear_orden.setText(_translate("FormTomarOrden", "CONFIRMAR Y ENVIAR A COCINA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormTomarOrden = QtWidgets.QWidget()
    ui = Ui_FormTomarOrden()
    ui.setupUi(FormTomarOrden)
    FormTomarOrden.show()
    sys.exit(app.exec_())
