# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistas/ventanasupervicion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSupervision(object):
    def setupUi(self, FormSupervision):
        FormSupervision.setObjectName("FormSupervision")
        FormSupervision.resize(750, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormSupervision)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(FormSupervision)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tbl_estado_ordenes = QtWidgets.QTableWidget(FormSupervision)
        self.tbl_estado_ordenes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_estado_ordenes.setObjectName("tbl_estado_ordenes")
        self.tbl_estado_ordenes.setColumnCount(3)
        self.tbl_estado_ordenes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_estado_ordenes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_estado_ordenes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_estado_ordenes.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tbl_estado_ordenes)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_estado_preparando = QtWidgets.QPushButton(FormSupervision)
        self.btn_estado_preparando.setObjectName("btn_estado_preparando")
        self.hboxlayout.addWidget(self.btn_estado_preparando)
        self.btn_estado_listo = QtWidgets.QPushButton(FormSupervision)
        self.btn_estado_listo.setObjectName("btn_estado_listo")
        self.hboxlayout.addWidget(self.btn_estado_listo)
        self.btn_cancelar_orden = QtWidgets.QPushButton(FormSupervision)
        self.btn_cancelar_orden.setStyleSheet("background-color: #f44336; color: white; font-weight: bold;")
        self.btn_cancelar_orden.setObjectName("btn_cancelar_orden")
        self.hboxlayout.addWidget(self.btn_cancelar_orden)
        self.verticalLayout.addLayout(self.hboxlayout)

        self.retranslateUi(FormSupervision)
        QtCore.QMetaObject.connectSlotsByName(FormSupervision)

    def retranslateUi(self, FormSupervision):
        _translate = QtCore.QCoreApplication.translate
        FormSupervision.setWindowTitle(_translate("FormSupervision", "TECLUSA - Monitor de Cocina"))
        self.label.setText(_translate("FormSupervision", "<b>Monitor de Órdenes Activas</b>"))
        item = self.tbl_estado_ordenes.horizontalHeaderItem(0)
        item.setText(_translate("FormSupervision", "No. Orden"))
        item = self.tbl_estado_ordenes.horizontalHeaderItem(1)
        item.setText(_translate("FormSupervision", "Estado Actual"))
        item = self.tbl_estado_ordenes.horizontalHeaderItem(2)
        item.setText(_translate("FormSupervision", "Total"))
        self.btn_estado_preparando.setText(_translate("FormSupervision", "👨‍🍳 Marcar \"En Preparación\""))
        self.btn_estado_listo.setText(_translate("FormSupervision", "🛎️ Marcar \"Lista para Entrega\""))
        self.btn_cancelar_orden.setText(_translate("FormSupervision", "🚫 Cancelar Orden (Anular)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSupervision = QtWidgets.QWidget()
    ui = Ui_FormSupervision()
    ui.setupUi(FormSupervision)
    FormSupervision.show()
    sys.exit(app.exec_())
