# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vistas/ventana_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaMenu(object):
    def setupUi(self, VentanaMenu):
        VentanaMenu.setObjectName("VentanaMenu")
        VentanaMenu.resize(430, 343)
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaMenu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(VentanaMenu)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(VentanaMenu)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(VentanaMenu)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(VentanaMenu)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtNombrePlatillo = QtWidgets.QLineEdit(VentanaMenu)
        self.txtNombrePlatillo.setObjectName("txtNombrePlatillo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtNombrePlatillo)
        self.nmbPrecio = QtWidgets.QSpinBox(VentanaMenu)
        self.nmbPrecio.setObjectName("nmbPrecio")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.nmbPrecio)
        self.cmbCategoriaPlatillo = QtWidgets.QComboBox(VentanaMenu)
        self.cmbCategoriaPlatillo.setObjectName("cmbCategoriaPlatillo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbCategoriaPlatillo)
        self.label_4 = QtWidgets.QLabel(VentanaMenu)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtDescripcion = QtWidgets.QTextEdit(VentanaMenu)
        self.txtDescripcion.setObjectName("txtDescripcion")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtDescripcion)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAgregar = QtWidgets.QPushButton(VentanaMenu)
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout.addWidget(self.btnAgregar)
        self.btnModificar = QtWidgets.QPushButton(VentanaMenu)
        self.btnModificar.setObjectName("btnModificar")
        self.horizontalLayout.addWidget(self.btnModificar)
        self.btnEliminar = QtWidgets.QPushButton(VentanaMenu)
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout.addWidget(self.btnEliminar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(VentanaMenu)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(VentanaMenu)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.txtBuscarPlatillo = QtWidgets.QLineEdit(VentanaMenu)
        self.txtBuscarPlatillo.setObjectName("txtBuscarPlatillo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtBuscarPlatillo)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.tblCatalogoAlimentos = QtWidgets.QTableView(VentanaMenu)
        self.tblCatalogoAlimentos.setObjectName("tblCatalogoAlimentos")
        self.verticalLayout.addWidget(self.tblCatalogoAlimentos)

        self.retranslateUi(VentanaMenu)
        QtCore.QMetaObject.connectSlotsByName(VentanaMenu)

    def retranslateUi(self, VentanaMenu):
        _translate = QtCore.QCoreApplication.translate
        VentanaMenu.setWindowTitle(_translate("VentanaMenu", "Form"))
        self.label_6.setText(_translate("VentanaMenu", "Formulario de Platillos"))
        self.label.setText(_translate("VentanaMenu", "Nombre del Platillo:"))
        self.label_2.setText(_translate("VentanaMenu", "Categoría:"))
        self.label_3.setText(_translate("VentanaMenu", "Precio ($):"))
        self.label_4.setText(_translate("VentanaMenu", "Descripción"))
        self.btnAgregar.setText(_translate("VentanaMenu", "Agregar"))
        self.btnModificar.setText(_translate("VentanaMenu", "Modificar"))
        self.btnEliminar.setText(_translate("VentanaMenu", "Eliminar"))
        self.label_5.setText(_translate("VentanaMenu", "Catálogo de Platillos"))
        self.label_7.setText(_translate("VentanaMenu", "Platillo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaMenu = QtWidgets.QWidget()
    ui = Ui_VentanaMenu()
    ui.setupUi(VentanaMenu)
    VentanaMenu.show()
    sys.exit(app.exec_())
